version: "3.8"
services:
  web:
    container_name: 5etools
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - .:/var/www/localhost/htdocs
